### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by zhudock** [tschf/dmdump#3]
I was able to get Windows support working in my fork. If there's any interest I'll submit a PR.

**Comment by tschf** [comment]
Nice :).. I'm not in Windows much, but would be happy to merge your additions. Was thinking to change to a single input (connect string) rather than all those separated out (host, port, sid, etc). I did this in my atom-build-oracle project, and I think it's a better approach. But doesn't look like it'd be too tricky to adjust the batch script to handle that when I get around to it.

**Comment by zhudock** [comment]
I actually had that same thought and just hadn't committed it yet. I'll take a look at atom-build-oracle and use that example
